### ISSUE TITLE
Init container failing

### ISSUE THREAD

**Issue by jhansen81** [Sitecore/Sitecore.Demo.Platform#217]
Hi,

Every time I run `docker-compose up -d`, everything finishes and the init container begins to run but fails pretty quickly with the following error.  I know in the documentation it says that the init container can finish before it's done and to just run it again, so I've done that several times but always with the same result.

init_1                 | info: Sitecore.Demo.Init.Jobs.JobStatus[0]
init_1                 |       <!DOCTYPE html><html><head><link href='/sitecore/images/favicon.ico' rel='shortcut icon' /><link hre
init_1                 | info: Sitecore.Demo.Init.Jobs.JobStatus[0]
init_1                 |       5/12/2022 6:39:56 PM Job status:
init_1                 | info: PublishItems[0]
init_1                 |       #30 5/12/2022 6:40:08 PM Publishing is in progress...
init_1                 | info: PublishItems[0]
init_1                 |       #31 5/12/2022 6:40:18 PM Publishing is in progress...
init_1                 | info: PublishItems[0]
init_1                 |       #32 5/12/2022 6:40:28 PM Publishing is in progress...
init_1                 | info: PublishItems[0]
init_1                 |       #33 5/12/2022 6:40:39 PM Publishing is in progress...
init_1                 | info: PublishItems[0]
init_1                 |       Publishing completed with the status: OK
init_1                 | info: PublishItems[0]
init_1                 |       #0 5/12/2022 6:40:50 PM Publishing is in progress...
init_1                 | info: PublishItems[0]
init_1                 |       #1 5/12/2022 6:41:00 PM Publishing is in progress...
init_1                 | info: PublishItems[0]
init_1                 |       #2 5/12/2022 6:41:10 PM Publishing is in progress...
init_1                 | info: PublishItems[0]
init_1                 |       #3 5/12/2022 6:41:20 PM Publishing is in progress...
init_1                 | info: PublishItems[0]
init_1                 |       Publishing completed with the status: OK
init_1                 | info: PublishItems[0]
init_1                 |       Created {"value":"b27f33fb-d31b-442d-bc14-2d59f427c24c"}
init_1                 | info: PublishItems[0]
init_1                 |       PublishItems() complete
init_1                 | info: RestartCM[0]
init_1                 |       RestartSitecore() http://cm started
init_1                 | info: RestartCM[0]
init_1                 |       OK
init_1                 | info: RestartCM[0]
init_1                 |       RestartSitecore() http://cm complete
init_1                 | fail: Sitecore.Demo.Init.Services.JobManagementManagementService[0]
init_1                 |       An error has occurred when running JobManagementManagementService
init_1                 |       System.Threading.Tasks.TaskCanceledException: The operation was canceled.
init_1                 |        ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
init_1                 |        ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
init_1                 |          --- End of inner exception stack trace ---
init_1                 |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
init_1                 |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
init_1                 |          at System.Net.Http.HttpConnection.FillAsync()
init_1                 |          at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
init_1                 |          at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
init_1                 |          --- End of inner exception stack trace ---
init_1                 |          at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
init_1                 |          at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
init_1                 |          at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
init_1                 |          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
init_1                 |          at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
init_1                 |          at Sitecore.Demo.Init.Jobs.RestartCD.Run() in C:\src\Jobs\RestartCD.cs:line 37
init_1                 |          at Sitecore.Demo.Init.Services.JobManagementManagementService.ExecuteAsync(CancellationToken stoppingToken) in C:\src\Services\JobManagementManagementService.cs:line 48

**Comment by jhansen81** [comment]
Persistence paid off and the fifth time got me beyond this error...
